// <auto-generated />
using System;
using FOKE.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FOKE.DataAccess.Migrations
{
    [DbContext(typeof(FOKEDBContext))]
    [Migration("20250605055342_AreaMemberTableChanged")]
    partial class AreaMemberTableChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FOKE.Entity.AreaMaster.DTO.AreaData", b =>
                {
                    b.Property<long>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AreaId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AreaId");

                    b.ToTable("AreaDatas");
                });

            modelBuilder.Entity("FOKE.Entity.AreaMember.DTO.AreaMember", b =>
                {
                    b.Property<long>("AreaMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AreaMemberId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserMemberId")
                        .HasColumnType("bigint");

                    b.HasKey("AreaMemberId");

                    b.HasIndex("AreaId");

                    b.HasIndex("UserMemberId");

                    b.ToTable("AreaMembers");
                });

            modelBuilder.Entity("FOKE.Entity.CampaignData.DTO.Campaign", b =>
                {
                    b.Property<long>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CampaignId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CollectionAdded")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberShipFee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("FOKE.Entity.CancelReasonMaster.DTO.CancelReasonData", b =>
                {
                    b.Property<long>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReasonId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReasonId");

                    b.ToTable("CancelReasonDatas");
                });

            modelBuilder.Entity("FOKE.Entity.DepartmentMaster.DTO.Department", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DepartmentId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FOKE.Entity.FileUpload.DTO.FileStorage", b =>
                {
                    b.Property<long>("FileStorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FileStorageId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FileStorageId");

                    b.ToTable("FileStorages");
                });

            modelBuilder.Entity("FOKE.Entity.FileUpload.DTO.MemberProfileData", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrgFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("FileStorageId");

                    b.ToTable("MemberProfileDatas");
                });

            modelBuilder.Entity("FOKE.Entity.Identity.DTO.LookUpTypeMaster", b =>
                {
                    b.Property<long>("LookUpTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LookUpTypeId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookUpTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LookUpTypeId");

                    b.ToTable("LookupTypeMasters");
                });

            modelBuilder.Entity("FOKE.Entity.Identity.DTO.LookupMaster", b =>
                {
                    b.Property<long>("LookUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LookUpId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookUpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LookUpTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LookUpId");

                    b.HasIndex("LookUpTypeId");

                    b.ToTable("LookupMasters");
                });

            modelBuilder.Entity("FOKE.Entity.Identity.DTO.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("LoggedInUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoggedInUserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("FOKE.Entity.Identity.DTO.Users", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ActiveSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoggedInDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FOKE.Entity.Localization.DTO.LocalizationResource", b =>
                {
                    b.Property<long>("LocalizationResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LocalizationResourceId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalizationResourceId");

                    b.ToTable("LocalizationResources");
                });

            modelBuilder.Entity("FOKE.Entity.MembershipData.DTO.MemberShipCancelled", b =>
                {
                    b.Property<long>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IssueId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("AmountRecieved")
                        .HasColumnType("bigint");

                    b.Property<long?>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BloodGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CampaignAmount")
                        .HasColumnType("bigint");

                    b.Property<long?>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<string>("CivilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ContactNo")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryCode")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GenderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HearAboutUsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PaymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProfessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferanceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RegistrationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WorkPlaceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("IssueId");

                    b.HasIndex("AreaId");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("UnitId");

                    b.HasIndex("ZoneId");

                    b.ToTable("MemberShipCancelledDatas");
                });

            modelBuilder.Entity("FOKE.Entity.MembershipData.DTO.MembershipAccepted", b =>
                {
                    b.Property<long>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IssueId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AmountRecieved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BloodGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CampaignAmount")
                        .HasColumnType("bigint");

                    b.Property<long?>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<string>("CivilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ContactNo")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryCodeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GenderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HearAboutUsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Memberfrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MembershipRequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PaymentReceivedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PaymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProfessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProffessionOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferanceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReferredBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("RegistrationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WorkPlaceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkYear")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkplaceOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("IssueId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("AreaId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WorkPlaceId");

                    b.HasIndex("ZoneId");

                    b.ToTable("MembershipAcceptedDatas");
                });

            modelBuilder.Entity("FOKE.Entity.MembershipData.DTO.MembershipFee", b =>
                {
                    b.Property<long>("MembershipFeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MembershipFeeId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("AmountToPay")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("Campaign")
                        .HasColumnType("bigint");

                    b.Property<string>("CollectionRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PaymentReceivedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("PaymentType")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MembershipFeeId");

                    b.ToTable("MembershipFees");
                });

            modelBuilder.Entity("FOKE.Entity.MembershipData.DTO.MembershipRejected", b =>
                {
                    b.Property<long>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IssueId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AmountRecieved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BloodGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CampaignAmount")
                        .HasColumnType("bigint");

                    b.Property<long?>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<string>("CivilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ContactNo")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryCodeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GenderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HearAboutUsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PaymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProfessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProffessionOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferanceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RegistrationId")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RejectionReasonId")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WorkPlaceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkYear")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkplaceOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("IssueId");

                    b.HasIndex("AreaId");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WorkPlaceId");

                    b.HasIndex("ZoneId");

                    b.ToTable("MembershipRejectedDatas");
                });

            modelBuilder.Entity("FOKE.Entity.MembershipRegistration.DTO.MembershipDetails", b =>
                {
                    b.Property<long>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MembershipId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BloodGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("CivilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ContactNo")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryCode")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GenderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HearAboutus")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProffessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProffessionOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WorkPlaceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkYear")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkplaceOther")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MembershipId");

                    b.ToTable("MembershipRequestDetails");
                });

            modelBuilder.Entity("FOKE.Entity.OperationManagement.DTO.FileMaster", b =>
                {
                    b.Property<long>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FileId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileRefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FolderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileId");

                    b.HasIndex("FileStorageId");

                    b.HasIndex("FolderId");

                    b.ToTable("FileMasters");
                });

            modelBuilder.Entity("FOKE.Entity.OperationManagement.DTO.FolderMaster", b =>
                {
                    b.Property<long>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FolderId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<string>("FolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FolderId");

                    b.HasIndex("FileStorageId");

                    b.ToTable("FolderMasters");
                });

            modelBuilder.Entity("FOKE.Entity.ProfessionData.DTO.Profession", b =>
                {
                    b.Property<long>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProfessionId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProffessionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProfessionId");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("FOKE.Entity.ProjectConfiguration.DTO.ProjectConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CONFIGCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONFIGKEY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectConfigurations");
                });

            modelBuilder.Entity("FOKE.Entity.RoleData.DTO.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FOKE.Entity.RoleData.DTO.RoleGroupClaim", b =>
                {
                    b.Property<long>("RoleGroupClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleGroupClaimId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ClaimValue")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleGroupClaimId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleGroupClaims");
                });

            modelBuilder.Entity("FOKE.Entity.Task_Manager.DTO.AttachmentData", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("AttachmentMasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("AttachmentModule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrgFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("FileStorageId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("FOKE.Entity.UnitData.DTO.Unit", b =>
                {
                    b.Property<long>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UnitId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UnitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("FOKE.Entity.UnitMember.UnitMember", b =>
                {
                    b.Property<long>("UnitMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UnitMemberId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UnitMemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitMembers");
                });

            modelBuilder.Entity("FOKE.Entity.WorkPlaceData.DTO.WorkPlace", b =>
                {
                    b.Property<long>("WorkPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkPlaceId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkPlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkPlaceId");

                    b.ToTable("WorkPlace");
                });

            modelBuilder.Entity("FOKE.Entity.ZoneMaster.DTO.Zone", b =>
                {
                    b.Property<long>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ZoneId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZoneName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZoneId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("FOKE.Entity.ZoneMember.ZoneMember", b =>
                {
                    b.Property<long>("ZoneMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ZoneMemberId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("ZoneMemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneMembers");
                });

            modelBuilder.Entity("FOKE.Entity.AreaMember.DTO.AreaMember", b =>
                {
                    b.HasOne("FOKE.Entity.AreaMaster.DTO.AreaData", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FOKE.Entity.Identity.DTO.Users", "UserId")
                        .WithMany()
                        .HasForeignKey("UserMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("UserId");
                });

            modelBuilder.Entity("FOKE.Entity.FileUpload.DTO.MemberProfileData", b =>
                {
                    b.HasOne("FOKE.Entity.FileUpload.DTO.FileStorage", "FileStorage")
                        .WithMany()
                        .HasForeignKey("FileStorageId");

                    b.Navigation("FileStorage");
                });

            modelBuilder.Entity("FOKE.Entity.Identity.DTO.LookupMaster", b =>
                {
                    b.HasOne("FOKE.Entity.Identity.DTO.LookUpTypeMaster", "LookUpTypeMaster")
                        .WithMany()
                        .HasForeignKey("LookUpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookUpTypeMaster");
                });

            modelBuilder.Entity("FOKE.Entity.Identity.DTO.UserSession", b =>
                {
                    b.HasOne("FOKE.Entity.Identity.DTO.Users", "User")
                        .WithMany()
                        .HasForeignKey("LoggedInUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FOKE.Entity.Identity.DTO.Users", b =>
                {
                    b.HasOne("FOKE.Entity.RoleData.DTO.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FOKE.Entity.MembershipData.DTO.MemberShipCancelled", b =>
                {
                    b.HasOne("FOKE.Entity.AreaMaster.DTO.AreaData", "AreaData")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("FOKE.Entity.ProfessionData.DTO.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.HasOne("FOKE.Entity.WorkPlaceData.DTO.WorkPlace", "WorkPlace")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.HasOne("FOKE.Entity.MembershipRegistration.DTO.MembershipDetails", "MembershipDetails")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FOKE.Entity.UnitData.DTO.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.HasOne("FOKE.Entity.ZoneMaster.DTO.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("AreaData");

                    b.Navigation("MembershipDetails");

                    b.Navigation("Profession");

                    b.Navigation("Unit");

                    b.Navigation("WorkPlace");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FOKE.Entity.MembershipData.DTO.MembershipAccepted", b =>
                {
                    b.HasOne("FOKE.Entity.Identity.DTO.Users", "Users")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("FOKE.Entity.AreaMaster.DTO.AreaData", "AreaData")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("FOKE.Entity.CampaignData.DTO.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.HasOne("FOKE.Entity.ProfessionData.DTO.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.HasOne("FOKE.Entity.MembershipRegistration.DTO.MembershipDetails", "MembershipDetails")
                        .WithMany()
                        .HasForeignKey("RegistrationId");

                    b.HasOne("FOKE.Entity.UnitData.DTO.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.HasOne("FOKE.Entity.WorkPlaceData.DTO.WorkPlace", "WorkPlace")
                        .WithMany()
                        .HasForeignKey("WorkPlaceId");

                    b.HasOne("FOKE.Entity.ZoneMaster.DTO.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("AreaData");

                    b.Navigation("Campaign");

                    b.Navigation("MembershipDetails");

                    b.Navigation("Profession");

                    b.Navigation("Unit");

                    b.Navigation("Users");

                    b.Navigation("WorkPlace");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FOKE.Entity.MembershipData.DTO.MembershipRejected", b =>
                {
                    b.HasOne("FOKE.Entity.AreaMaster.DTO.AreaData", "AreaData")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("FOKE.Entity.ProfessionData.DTO.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.HasOne("FOKE.Entity.MembershipRegistration.DTO.MembershipDetails", "MembershipDetails")
                        .WithMany()
                        .HasForeignKey("RegistrationId");

                    b.HasOne("FOKE.Entity.UnitData.DTO.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.HasOne("FOKE.Entity.WorkPlaceData.DTO.WorkPlace", "WorkPlace")
                        .WithMany()
                        .HasForeignKey("WorkPlaceId");

                    b.HasOne("FOKE.Entity.ZoneMaster.DTO.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("AreaData");

                    b.Navigation("MembershipDetails");

                    b.Navigation("Profession");

                    b.Navigation("Unit");

                    b.Navigation("WorkPlace");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FOKE.Entity.OperationManagement.DTO.FileMaster", b =>
                {
                    b.HasOne("FOKE.Entity.FileUpload.DTO.FileStorage", "FileStorage")
                        .WithMany()
                        .HasForeignKey("FileStorageId");

                    b.HasOne("FOKE.Entity.OperationManagement.DTO.FolderMaster", "FolderMaster")
                        .WithMany()
                        .HasForeignKey("FolderId");

                    b.Navigation("FileStorage");

                    b.Navigation("FolderMaster");
                });

            modelBuilder.Entity("FOKE.Entity.OperationManagement.DTO.FolderMaster", b =>
                {
                    b.HasOne("FOKE.Entity.FileUpload.DTO.FileStorage", "FileStorage")
                        .WithMany()
                        .HasForeignKey("FileStorageId");

                    b.Navigation("FileStorage");
                });

            modelBuilder.Entity("FOKE.Entity.RoleData.DTO.RoleGroupClaim", b =>
                {
                    b.HasOne("FOKE.Entity.RoleData.DTO.Role", "Role")
                        .WithMany("RoleGroupClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FOKE.Entity.Task_Manager.DTO.AttachmentData", b =>
                {
                    b.HasOne("FOKE.Entity.FileUpload.DTO.FileStorage", "FileStorage")
                        .WithMany()
                        .HasForeignKey("FileStorageId");

                    b.Navigation("FileStorage");
                });

            modelBuilder.Entity("FOKE.Entity.UnitMember.UnitMember", b =>
                {
                    b.HasOne("FOKE.Entity.MembershipData.DTO.MembershipAccepted", "MembershipId")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FOKE.Entity.UnitData.DTO.Unit", "unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipId");

                    b.Navigation("unit");
                });

            modelBuilder.Entity("FOKE.Entity.ZoneMember.ZoneMember", b =>
                {
                    b.HasOne("FOKE.Entity.MembershipData.DTO.MembershipAccepted", "MembershipId")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FOKE.Entity.ZoneMaster.DTO.Zone", "zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipId");

                    b.Navigation("zone");
                });

            modelBuilder.Entity("FOKE.Entity.RoleData.DTO.Role", b =>
                {
                    b.Navigation("RoleGroupClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
